In [1]:
import torch

In [2]:
a = torch.randn(5,5)
b = torch.randn(5,5)
print(a)
print(b)

tensor([[-1.2361,  1.4032,  0.3739, -0.2079, -0.7522],
        [ 0.8709, -1.9554,  1.8369, -0.7598,  0.1337],
        [ 0.3179,  0.1379, -0.8552, -0.0577, -1.0689],
        [ 0.1177, -0.8105,  1.2155, -0.7730, -0.5495],
        [ 1.9775, -0.0377,  0.5017,  1.7405, -0.6458]])
tensor([[ 1.5317,  1.0740,  0.0590, -0.9462,  0.4884],
        [-0.3518, -1.3349, -1.8504,  3.4326,  0.4598],
        [ 1.0741, -0.1704,  0.2249, -1.3057,  0.1200],
        [ 0.6461,  0.7064, -0.4347,  0.1357, -0.5036],
        [-0.0154,  1.1200,  0.9328, -0.0529,  2.1521]])


In [3]:
another_tensor = a[2,2]
print(another_tensor)

python_value = a[2,2].item()
print(python_value)

tensor(-0.8552)
-0.8551638722419739


In [8]:
c = a.mm(b)
print(c)

tensor([[ -2.1083,  -4.2537,  -3.1966,   5.5096,  -1.4277],
        [  3.5020,   2.8457,   4.5378, -10.0448,   0.4170],
        [ -0.5010,  -0.9348,  -1.4008,   1.3379,  -2.1552],
        [  1.2801,  -0.1602,   1.6034,  -4.5565,  -0.9627],
        [  4.7155,   2.5949,  -1.0599,  -2.3850,  -1.2575]])


In [12]:
torch.get_autocast_gpu_dtype.__name__

'get_autocast_gpu_dtype'