### 5. Exercise

In [8]:
import numpy as np

def neural_network(inputs, weights):
    """
     Takes an input vector and runs it through a 1-layer neural network
     with a given weight matrix and returns the output.

     Arg:
       inputs - 2 x 1 NumPy array
       weights - 2 x 1 NumPy array
     Returns (in this order):
       out - a 1 x 1 NumPy array, representing the output of the neural network
    """
    #Your code here

    x = inputs
    w = weights

    print("Input: ",x)
    print("Weights: ", w)
    print("Weights.T: ",w.T)
    print("Output: ",np.dot(w.T,x))

    z = np.tanh(np.dot(w.T, x))
    return z

    


In [9]:
neural_network(np.array([[0.86183139],[0.54340972]]), np.array([[0.61107849],[0.79371795]]))

Input:  [[0.86183139]
 [0.54340972]]
Weights:  [[0.61107849]
 [0.79371795]]
Weights.T:  [[0.61107849 0.79371795]]
Output:  [[0.95796067]]


array([[0.74336584]])

### 6. Exercise

In [10]:
def scalar_function(x, y):
    """
    Returns the f(x,y) defined in the problem statement.
    """
    if x<=y:
        return x*y
    else:
        return x/y
    


In [11]:
def vector_function(x, y):
    """
    Make sure vector_function can deal with vector input x,y 
    """
    vectorized = np.vectorize(scalar_function)
    return vectorized(x,y)


### 4. Exercise

In [ ]:
def randomization(n):
    """
    Arg:
      n - an integer
    Returns:
      A - a randomly-generated nx1 Numpy array.
    """
    return np.random.random([n,1])


In [22]:
randomization(5)

array([[0.70108675],
       [0.88985786],
       [0.78159785],
       [0.66266356],
       [0.12546608]])

In [ ]:
def operations(h, w):
    """
    Takes two inputs, h and w, and makes two Numpy arrays A and B of size
    h x w, and returns A, B, and s, the sum of A and B.

    Arg:
      h - an integer describing the height of A and B
      w - an integer describing the width of A and B
    Returns (in this order):
      A - a randomly-generated h x w Numpy array.
      B - a randomly-generated h x w Numpy array.
      s - the sum of A and B.
    """

    A = np.random.random([h,w])
    B = np.random.random([h,w])
    s = A+B
    
    return A, B, s

In [30]:
np.random.random([5,2])

array([[0.58759598, 0.47946321],
       [0.57761444, 0.81798283],
       [0.86086675, 0.4506402 ],
       [0.69113023, 0.14591844],
       [0.83510197, 0.52284386]])

In [ ]:
def norm(A, B):
    """
    Takes two Numpy column arrays, A and B, and returns the L2 norm of their
    sum.

    Arg:
      A - a Numpy array
      B - a Numpy array
    Returns:
      s - the L2 norm of A+B.
    """
    s = np.linalg.norm(A+B)
    return s


In [32]:
norm(np.array([3,4]),np.array([4,5]))

np.float64(11.40175425099138)